import enum


class SystemRole(str, enum.Enum):
    STATE_ADMIN = "STATE_ADMIN"
    DEPARTMENT_ADMIN = "DEPARTMENT_ADMIN"
    FIELD_ENGINEER = "FIELD_ENGINEER"
    MAINTENANCE_OFFICER = "MAINTENANCE_OFFICER"
    CONTRACTOR = "CONTRACTOR"


class AdminUnitLevel(str, enum.Enum):
    STATE = "STATE"
    REGION_CIRCLE = "REGION_CIRCLE"
    DIVISION = "DIVISION"
    SUB_DIVISION = "SUB_DIVISION"
    SECTION_FIELD_OFFICE = "SECTION_FIELD_OFFICE"


class AssetTypeCode(str, enum.Enum):
    ROAD = "ROAD"
    BRIDGE = "BRIDGE"
    CULVERT = "CULVERT"
    BUILDING = "BUILDING"
    PUBLIC_STRUCTURE = "PUBLIC_STRUCTURE"
    OTHER_FIXED_ASSET = "OTHER_FIXED_ASSET"


class GeometryKind(str, enum.Enum):
    POINT = "POINT"
    LINESTRING = "LINESTRING"
    POLYGON = "POLYGON"


class LifecycleStatus(str, enum.Enum):
    PLANNED = "PLANNED"
    SANCTIONED = "SANCTIONED"
    UNDER_CONSTRUCTION = "UNDER_CONSTRUCTION"
    COMMISSIONED = "COMMISSIONED"
    OPERATIONAL = "OPERATIONAL"
    INSPECTION_REQUIRED = "INSPECTION_REQUIRED"
    MAINTENANCE_REQUIRED = "MAINTENANCE_REQUIRED"
    UNDER_MAINTENANCE = "UNDER_MAINTENANCE"
    RENOVATION_UPGRADATION = "RENOVATION_UPGRADATION"
    RETIRED = "RETIRED"
    DECOMMISSIONED = "DECOMMISSIONED"


class ConditionRating(str, enum.Enum):
    GOOD = "GOOD"
    FAIR = "FAIR"
    POOR = "POOR"
    CRITICAL = "CRITICAL"


class InspectionStatus(str, enum.Enum):
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    RETURNED = "RETURNED"


class FindingSeverity(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class MaintenanceType(str, enum.Enum):
    PREVENTIVE = "PREVENTIVE"
    CORRECTIVE = "CORRECTIVE"
    EMERGENCY = "EMERGENCY"


class MaintenancePriority(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    URGENT = "URGENT"


class MaintenanceRequestStatus(str, enum.Enum):
    OPEN = "OPEN"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CONVERTED_TO_WORK_ORDER = "CONVERTED_TO_WORK_ORDER"
    CLOSED = "CLOSED"


class WorkOrderStatus(str, enum.Enum):
    CREATED = "CREATED"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    VERIFIED = "VERIFIED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class ApprovalStatus(str, enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    RETURNED = "RETURNED"


class ApprovalEntityType(str, enum.Enum):
    INSPECTION = "INSPECTION"
    MAINTENANCE_REQUEST = "MAINTENANCE_REQUEST"
    LIFECYCLE_TRANSITION = "LIFECYCLE_TRANSITION"
    PROJECT = "PROJECT"


class ProjectStatus(str, enum.Enum):
    PROPOSED = "PROPOSED"
    SANCTIONED = "SANCTIONED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CLOSED = "CLOSED"


class DocumentType(str, enum.Enum):
    LAND_RECORD = "LAND_RECORD"
    OWNERSHIP = "OWNERSHIP"
    DPR = "DPR"
    DRAWING = "DRAWING"
    APPROVAL = "APPROVAL"
    ESTIMATE = "ESTIMATE"
    COMPLETION_CERTIFICATE = "COMPLETION_CERTIFICATE"
    INSPECTION_REPORT = "INSPECTION_REPORT"
    MAINTENANCE_REPORT = "MAINTENANCE_REPORT"
    PHOTOGRAPH = "PHOTOGRAPH"
    OTHER = "OTHER"


class NotificationEvent(str, enum.Enum):
    INSPECTION_DUE = "INSPECTION_DUE"
    CRITICAL_CONDITION = "CRITICAL_CONDITION"
    MAINTENANCE_DUE = "MAINTENANCE_DUE"
    OVERDUE_WORK_ORDER = "OVERDUE_WORK_ORDER"
    APPROVAL_PENDING = "APPROVAL_PENDING"
    PROJECT_MILESTONE = "PROJECT_MILESTONE"
    GRIEVANCE_FILED = "GRIEVANCE_FILED"


class GrievanceCategory(str, enum.Enum):
    STRUCTURAL_DAMAGE = "STRUCTURAL_DAMAGE"
    POTHOLE = "POTHOLE"
    WATER_LOGGING = "WATER_LOGGING"
    TREE_HAZARD = "TREE_HAZARD"
    ENCROACHMENT = "ENCROACHMENT"
    SAFETY_HAZARD = "SAFETY_HAZARD"
    ELECTRICAL_HAZARD = "ELECTRICAL_HAZARD"
    OTHER = "OTHER"


class GrievanceStatus(str, enum.Enum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    REJECTED = "REJECTED"


class TenderStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    BIDDING_CLOSED = "BIDDING_CLOSED"
    AWARDED = "AWARDED"
    CANCELLED = "CANCELLED"


class TenderBidStatus(str, enum.Enum):
    SUBMITTED = "SUBMITTED"
    SHORTLISTED = "SHORTLISTED"
    REJECTED = "REJECTED"
    AWARDED = "AWARDED"
